services:
    jenkins:
        image: jenkins/jenkins
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - /var/jenkins_home
        restart: unless-stopped
    
    mails:
        image: mailhog/mailhog
        ports:
            - "8025:8025"
        restart: unless-stopped